default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: phadder_2_0_api_development

test:
  <<: *default
  database: phadder_2_0_api_test

production:
  <<: *default
  database: phadder_2_0_api_production
  username: phadder_2_0_api
  password: <%= ENV['PHADDER_2_0_API_DATABASE_PASSWORD'] %>
